users:
  - name: ubuntu
    ssh_authorized_keys:  #공개키
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINQ5u2RYVOMWmkayrgBlrZBPmFc6lBTRyCZgYUsgJpGW dhkang@NO-202412-117.local"
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash